name: Release
on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    name: Deploy to PyPi
    steps:
      - uses: actions/checkout@v2.3.3
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
          architecture: x64

      - name: Install dependencies
        run: pip install poetry==1.0.9

      #      - run: python3 -m black .
      - run: poetry install
      - run: poetry run pytest
      - run: poetry build
      - run: poetry publish --username=__token__ --password=${{ secrets.PYPI_TOKEN }}
